engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.angular-chart"
exclude_paths:
- "**.min.angular-chart"
- karma*.conf.angular-chart
- prism/**/*
- test/**/*
- .*
